# Generated by Django 3.1.1 on 2020-10-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201010_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='Url',
            new_name='url',
        ),
    ]
